module.exports = {
  PORT: process.env.PORT || 5008,
  clientId: "900a288f7bb24948b9dc2fbf7881ceec",
  clientSecret: "637265a785394c439cf9a5c11f2681d6",
  oppoTestApi: "https://global-search-sg-test.wanyol.com/gis/open/income/add",
  oppoPrdApi: "https://api-gl.open.heytapmobile.com/gis/open/income/add",
  testApiKey: "89fc80d5a056d8d69e18b4648fd32bd0",
  testApiSecret: "Zh5J9Blwkl64uQ6GGXSb2ET25Ruwkk269slGSaDuRYd/ySx5TA+bBQ==",
  prdApiKey: "6c622e322d8f7a87228cf36d5d3e1226",
  prdApiSecret: "/kd7+8A+F7gnm+SeQgrDY7i98o30ggccjzrr1zBLYS9/ySx5TA+bBQ==",

  bsApi: (() => {
    const baseUrl = "https://backstage.taboola.com/backstage/api/1.0";
    const endpoints = [
      "oppo-lockscreen-jp",
      "oppo-lockscreen-tw",
      "oppo-lockscreen-it",
      "oppo-lockscreen-fallback",
      "oppo-lockscreen-mx",
      "oppo-lockscreen-eg",
      "oppo-lockscreen-tr",
      "oppo-lockscreen-gb",
      "oppo-lockscreen-pl",
      "oppo-lockscreen-es",
      "oppo-lockscreen-th",
      "oppo-lockscreen-fr",
      "oppo-lockscreen-au",
      "oppo-lockscreen-in-en",
      "oppo-lockscreen-ae",
      "oppo-lockscreen-vn",
      "oppo-lockscreen-ch",
      "oppo-lockscreen-de",
      "oppo-lockscreen-pk",
      "oppo-lockscreen-id",
      "oppo-lockscreen-nl",
      "oppo-lockscreen-sg",
      "oppo-lockscreen-sa",
      "oppo-lockscreen-pt",
      "oppo-browser-india-hindi",
      "oppo-lockscreen-ph",
      "oppo-browser-fallback",
      "oppo-lockscreen-my-en",
      "oppo-lockscreen-be",
      "oppo-lockscreen-co",
      "oppo-browser-india-en",
      "oppo-lockscreen-ma",
      "oppo-lockscreen-gr",
      "oppo-lockscreen-my",
      "oppo-lockscreen-in-mix",
      "oppo-search-india-top-news",
      "oppo-lockscreen-ie",
      "oppo-lockscreen-ar",
      "oppo-browser-philippines",
      "oppo-lockscreen-at",
      "oppo-browser-malaysia-en",
      "oppo-search-id-top-news",
      "oppo-search-vn-top-news",
      "oppo-search-th-top-news",
      "oppo-browser-india-tamil",
      "oppo-lockscreen-fi",
      "oppo-browser-india-marathi",
      "oppo-search-ph-top-news",
      "oppo-lockscreen-se",
      "oppo-search-sp-top-news",
      "oppo-search-sg-top-news",
      "oppo-lockscreen-dk",
      "oppo-lockscreen-lu",
      "oppo-search-it-top-news",
      "oppo-search-uk-top-news",
      "oppo-search-ma-top-news",
      "oppo-search-fr-top-news",
      "oppo-search-india-top-news-hi",
      "oppo-browser-thailand",
      "oppo-search-ge-top-news",
      "oppo-browser-arabic-fallback",
      "oppo-browser-spanish-fallback-latam",
      "oppo-browser-malaysia-malay",
      "oppo-browser-india-en-push-feed",
      "oneplus-lockscreen-english-fallback",
      "oppo-browser-german-fallback",
      "oppo-browser-french-fallback",
      "oppo-browser-spanish-fallback",
      "oppo-browser-italian-fallback",
      "oppo-browser-indonesia",
      // "oppo-superapp-fallback-eng",
      "oppo-browser-philippine-push-feed",
      "oppo-browser-malaysia-push-feed",
      "oppo-lockscreen-is",
      "oppo-browser-india-hindi-push-feed",
      "oppo-browser-india-en-push",
      "oppo-browser-portuguese-fallback",
      "oppo-browser-indonesia-push-feed",
      "oppo-browser-philippine-push",
      "oppo-browser-india-hindi-push",
      "oppo-browser-indonesia-push",
      "oppo-browser-thailand-covid19",
    ];

    return endpoints.map(
      (endpoint) =>
        `${baseUrl}/${endpoint}/reports/taboola-news-summary-api/dimensions/by_day`
    );
  })(),
  dbHost: "proxysql-office.taboolasyndication.com",
  dbPort: 6033,
  dbUser: "liang.x",
  dbPassword: "Taboola#123",
  dbName: "Taboola TRC",
};
